services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - UID=1001
        - GID=1001
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/user/.Xauthority
      - .:/home/user/ros2_ws/src/display
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=33
      - DISPLAY_SCALE=1.5
    working_dir: /home/user/ros2_ws
    # command: ros2 run rqt_image_view rqt_image_view
    # command:
    #   - bash
    #   - -c
    #   - |
    #     colcon build --symlink-install
    #     source /home/user/ros2_ws/install/setup.bash
    #     ros2 run display main
    tty: true
