ARG ROS_DISTRO=humble

FROM ros:${ROS_DISTRO}-ros-base

RUN apt-get update && apt-get install -y\
    libopencv-dev \
    python3-pip

RUN pip install \
    opencv-python \
    cv_bridge \
    matplotlib

ARG UID
ARG GID

RUN groupadd -g ${GID} user && \
    useradd -m -s /bin/bash -u ${UID} -g ${GID} user

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/user/.bashrc

USER user
RUN mkdir -p /home/user/ros2_ws/src
WORKDIR /home/user/
